transformation_matrix:
- - -0.204758567187581
  - -0.978812509709234
  - -0.7008517409048839
- - 0.978812509709234
  - -0.204758567187581
  - -3.67140434155935
lidar_pose:
  position_xy:
  - -0.7008517409048839
  - -3.67140434155935
  rotation_z_deg: 101.81536617022307